language: php
php:
  - '7.4'

sudo:     true

addons:
  mariadb: '10.3'

before_install:
  - mysql --version

install:
  - rm -f composer.lock
  - composer self-update
  - composer update

script:
  - ./bin/phing unit
